# proj info
site_name: 'TurtleCoin Wiki'
site_description: 'Wiki for TurtleCoin'
site_author: 'TurtleCoin'
site_url: https://docs.turtlecoin.lol/

# repo
repo_name: 'turtlecoin/sajodocs'
repo_url: 'https://github.com/turtlecoin/sajodocs'

# copyright
copyright: 'Copyright 2019 TurtleCoin'

# config
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/fav.png'
  palette:
    primary: 'green'
    accent: 'light green'
  language: 'en'
  direction: 'ltr'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html

# customization
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/turtlecoin'

# extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  #pymdown extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# directory org
nav:
    - Home:
      - Home: index.md
      - Getting Started: Getting-Started.md
      - Contributors: Contributors.md
    - About:
      - About TurtleCoin: about/About-TurtleCoin.md
      - Background and History: about/Background-and-History.md
      - Our Community: about/Community.md
      - Contributing: about/Contributing.md
      - Technical Data: about/Technical-Data.md
      - Timeline: about/Timeline.md
    - FAQ:
      - Frequently Asked Questions: Frequently-Asked-Questions.md
    - Guides:
      - Using trtlbot++: guides/Using-trtlbot-plus-plus.md
      - RainBorg? Wat Dat?: guides/RainBorg-Wat-Dat.md
      - Forking TurtleCoin: guides/Forking-Turtlecoin.md
      - Running TurtleCoind on a Pi: guides/TurtleCoind-on-Pi.md
      - Mining:
        - How to Mine TRTL: guides/mining/Mining.md
        - XMR-Stak: guides/mining/XMR-Stak-Guide.md
        - XMR-Stak on Linux: guides/mining/XMR-Stak-Linux-Guide.md
        - XMRig: guides/mining/XMRIG-Guide.md
        - Pools: guides/mining/Pools.md
        - Cloud Mining: guides/mining/Cloud-Mining.md
        - Mining with a SBC: guides/mining/Mining-with-SBC.md
        - Mining on your Phone:
          - How to Mine TRTL on your Phone: guides/mining/mobile-mining/Mining-with-Phone.md
          - Using Tony Monero: guides/mining/mobile-mining/Using-Tony-Monero.md
          - Using AA Miner: guides/mining/mobile-mining/Using-AA-Miner.md
      - Wallets:
        - Making a Wallet: guides/wallets/Making-a-Wallet.md
        - GUI Wallet:
          - Nest Wallet: guides/wallets/Using-nest-wallet.md
        - CLI Wallet:
          - zedwallet: guides/wallets/Using-zedwallet.md
          - Using Checkpoints: guides/wallets/Using-checkpoints.md
        - Web Wallet:
          - Using a Web Wallet: guides/wallets/Using-a-Web-Wallet.md
          - Shellnet: guides/wallets/Using-shellnet.md
        - Making a Paper Wallet: guides/wallets/Making-a-paper-wallet.md
        - Recovering your Wallet: guides/wallets/recovering-your-wallet.md
        - Using Remote Nodes: guides/wallets/Using-remote-nodes.md
      - CryptoCurrency Fundamentals:
        - Smart Contracts: guides/crypto-funda/smart-contract.md
    - For Developers:
      - Resources: developers/Resources.md
      - Compiling from Source: developers/Compiling-from-Source.md
      - TurtleCoind behind HAProxy: developers/TurtleCoind-behind-HAProxy.md
